version: '3.8'

services:
  react-crm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: https://yklzzuoniimpqjqqymlu.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrbHp6dW9uaWltcHFqcXF5bWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzgxNDksImV4cCI6MjA1ODY1NDE0OX0.kShXk8AgMUNF1eZpDxK9FiqUJK1KNRTM-Tr-jZTNIc4
    ports:
      - "80:80"
    restart: unless-stopped
