services:
  react-crm:
    image: ghcr.io/taidio1/easymovecrm:latest
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=80
