server {
    listen [::]:80 ssl;
    server_name easymove.bieda.it;

    ssl_certificate /etc/letsencrypt/live/easymove.bieda.it/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/easymove.bieda.it/privkey.pem;

    location / {
        proxy_pass https://easymove.bieda.it:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
